#TODO: Move this configuration into package level.
#TODO: For example into config/packages/healthcheck.yaml

healthcheck:
    resource: ../../src/Healthcheck/
    type: annotation

institution:
    resource: ../../src/OpenSkos/Institution/Controller
    type: annotation

set:
    resource: ../../src/OpenSkos/Set/Controller
    type: annotation

conceptscheme:
    resource: ../../src/OpenSkos/ConceptScheme/Controller
    type: annotation

label:
    resource: ../../src/OpenSkos/Label/Controller
    type: annotation

concept:
    resource: ../../src/OpenSkos/Concept/Controller
    type: annotation

role:
    resource: ../../src/OpenSkos/Role/Controller
    type: annotation

user:
    resource: ../../src/OpenSkos/User/Controller
    type: annotation

relation:
    resource: ../../src/OpenSkos/RelationType/Controller
    type: annotation

status:
    resource: ../../src/OpenSkos/Status/Controller
    type: annotation

vocabulary:
    resource: ../../src/OpenSkos/Vocabulary/Controller
    type: annotation
