#TODO: Move this configuration into package level.
#TODO: For example into config/packages/healthcheck.yaml

healthcheck:
    resource: ../../src/Healthcheck/
    type: annotation

institution:
    resource: ../../src/Institution/Controller
    type: annotation

set:
    resource: ../../src/Set/Controller
    type: annotation
