#TODO: Move this configuration into package level.
#TODO: For example into config/packages/healthcheck.yaml

healthcheck:
    resource: ../../src/Healthcheck/
    type: annotation

institution:
    resource: ../../src/OpenSkos/Institution/Controller
    type: annotation

set:
    resource: ../../src/OpenSkos/Set/Controller
    type: annotation

conceptscheme:
    resource: ../../src/OpenSkos/ConceptScheme/Controller
    type: annotation


concept:
    resource: ../../src/OpenSkos/Concept/Controller
    type: annotation

role:
    resource: ../../src/OpenSkos/Role/Controller
    type: annotation

relation:
    resource: ../../src/OpenSkos/RelationType/Controller
    type: annotation
