version: "3.5"

services:
  fpm:
    build:
      context: ..
      dockerfile: docker/fpm/Dockerfile
    networks:
      - default
      - openskos
    env_file:
      - fpm/symfony.env
    volumes:
      - ../:/app

  nginx:
    build: nginx
    env_file:
      - nginx/default.env
    ports:
      - 9020:80
    volumes:
      - ./nginx:/app:ro

networks:
  openskos:
    external:
      name: openskos